---- ###################
---- ### 새 생성 여부 ###
---- ###################
DROP TABLE IF EXISTS public."TB_HOSPITAL";

DROP TABLE IF EXISTS public."TB_CROSSWALK";

DROP TABLE IF EXISTS public."TB_ACADEMY";

DROP TABLE IF EXISTS public."TB_LIVING_INFO";

DROP TABLE IF EXISTS public."TB_PARIS";

DROP TABLE IF EXISTS public."TB_PARKING";

DROP TABLE IF EXISTS public."TB_SALES";

DROP TABLE IF EXISTS public."TB_SCHOOL";

DROP TABLE IF EXISTS public."TB_SELLING_AREA";

DROP TABLE IF EXISTS public."TB_STATION";

DROP TABLE IF EXISTS public."TB_STOP";

DROP TABLE IF EXISTS public."TB_TOUR";
--
---- 학원 테이블
---- Table: public.TB_ACADEMY
--CREATE TABLE IF NOT EXISTS public."TB_ACADEMY" (
--    "ACADEMY_ID" serial primary key,
--    "SHOP_NUM" VARCHAR(300),
--    "SHOP_NAME" VARCHAR(300),
--    "SHOP_TYPE" VARCHAR(300),
--    "STANDARD_CODE" VARCHAR(300),
--    "STANDARD_NAME" VARCHAR(300),
--    "CITY_CODE" integer,
--    "CITY_NAME" VARCHAR(300),
--    "ROAD_NAME" VARCHAR(300),
--    "BUILDING_NAME" VARCHAR(300),
--    "ROAD_ADDRESS" VARCHAR(300),
--    "LATITUDE" double precision,
--    "LONGITUDE" double precision
--) TABLESPACE pg_default;
--
--ALTER TABLE
--    IF EXISTS public."TB_ACADEMY" OWNER to postgres;
--
---- 횡당보도 테이블
---- Table: public.TB_CROSSWALK
--CREATE TABLE IF NOT EXISTS public."TB_CROSSWALK" (
--    "CROSSWALK_ID" serial PRIMARY KEY,
--    "DO_NAME" VARCHAR(300),
--    "CITY_NAME" VARCHAR(300),
--    "ROAD_NAME" VARCHAR(300),
--    "BRANCH_ADDRESS" VARCHAR(300),
--    "MANAGE_NUM" VARCHAR(300),
--    "LATITUDE" double precision,
--    "LONGITUDE" double precision
--) TABLESPACE pg_default;
--
--ALTER TABLE
--    IF EXISTS public."TB_CROSSWALK" OWNER to postgres;
--
---- 병원 테이블
---- Table: public.TB_HOSPITAL
--CREATE TABLE IF NOT EXISTS public."TB_HOSPITAL" (
--    "HOSPITAL_ID" serial primary key,
--    "GOVERNMENT_CODE" integer,
--    "MANAGE_CODE" VARCHAR(300),
--    "LICENSE_DATE" VARCHAR(300),
--    "BUSINESS_STATUS" VARCHAR(300),
--    "STATE_CODE" integer,
--    "STATE_NAME" VARCHAR(300),
--    "TEL" VARCHAR(300),
--    "ROAD_ADDRESS" VARCHAR(300),
--    "BUSINESS_NAME" VARCHAR(300),
--    "BUSINESS_TYPE" VARCHAR(300),
--    latitude double precision,
--    longitude double precision
--) TABLESPACE pg_default;
--
--ALTER TABLE
--    IF EXISTS public."TB_HOSPITAL" OWNER to postgres;
--
---- 거주 세대 테이블
---- Table: public.TB_LIVING_INFO
--CREATE TABLE IF NOT EXISTS public."TB_LIVING_INFO" (
--    "LVN_ID" serial primary key,
--    "LVN_ADDRESS" VARCHAR(300),
--    "LVN_NAME" VARCHAR(300),
--    "LVN_COUNT" integer,
--    "LVN_FAMILY" integer,
--    "LVN_DATE" VARCHAR(300),
--    latitude double precision,
--    longitude double precision
--) TABLESPACE pg_default;
--
--ALTER TABLE
--    IF EXISTS public."TB_LIVING_INFO" OWNER to postgres;
--
---- 파리바게트 테이블
---- Table: public.TB_PARIS
--CREATE TABLE IF NOT EXISTS public."TB_PARIS" (
--    "PARIS_ID" serial primary key,
--    "PARIS_NAME" VARCHAR(300),
--    "PARIS_ADDRESS" VARCHAR(300),
--    latitude double precision,
--    longitude double precision
--) TABLESPACE pg_default;
--
--ALTER TABLE
--    IF EXISTS public."TB_PARIS" OWNER to postgres;
--
---- 주차장 정보 테이블
---- Table: public.TB_PARKING
--CREATE TABLE IF NOT EXISTS public."TB_PARKING" (
--    "PARKING_ID" serial primary key,
--    "MANAGE_NUMBER" VARCHAR(300),
--    "PARKING_NAME" VARCHAR(300),
--    "PARKING_CLASS" VARCHAR(300),
--    "PARKING_TYPE" VARCHAR(300),
--    "ROAD_ADDRESS" VARCHAR(300),
--    "BRANCH_ADDRESS" VARCHAR(300),
--    "PARKING_SAPCE" integer,
--    "TEL" VARCHAR(300),
--    "LATITUDE" double precision,
--    "LONGITUDE" double precision
--) TABLESPACE pg_default;
--
--ALTER TABLE
--    IF EXISTS public."TB_PARKING" OWNER to postgres;
--
---- 상권 정보 테이블
---- Table: public.TB_SALES
--CREATE TABLE IF NOT EXISTS public."TB_SALES" (
--    "COMM_ID" serial primary key,
--    "BASE_YEAR" integer,
--    "BASE_QUARTER" integer,
--    "COMM_NAME" VARCHAR(300),
--    "INDUSTRY_CODE" integer,
--    "INDUSTRY_NAME" VARCHAR(300),
--    "SALE_AMT" integer,
--    "SALE_NUM" integer,
--    "ROAD_ADDRESS" VARCHAR(300),
--    latitude double precision,
--    longitude double precision
--) TABLESPACE pg_default;
--
--ALTER TABLE
--    IF EXISTS public."TB_SALES" OWNER to postgres;
--
---- 학교 정보 테이블
---- Table: public.TB_SCHOOL
--CREATE TABLE IF NOT EXISTS public."TB_SCHOOL" (
--    "SCHOOL_ID" serial primary key,
--    "FACILITY_EDU_CODE" integer,
--    "FACILITY_EDU_NAME" VARCHAR(300),
--    "OFFICE_EDU_CODE" integer,
--    "OFFICE_EDU_NAME" VARCHAR(300),
--    "DO_CODE" integer,
--    "DO_NAME" VARCHAR(300),
--    "CITY_CODE" integer,
--    "CITY_NAME" VARCHAR(300),
--    "SCHOOL_NAME" VARCHAR(300),
--    "PUBLIC_PRIVATE" VARCHAR(300),
--    "EST_TYPE" VARCHAR(300),
--    "EST_DATE" VARCHAR(300),
--    "SCHOOL_CHAR" VARCHAR(300),
--    "DAY_NIGHT" VARCHAR(300),
--    "NUM_CLASS" integer,
--    "NUM_STUDENT" integer,
--    "NUM_TEACHER" integer,
--    "NUM_SPECIAL_CLASS" integer,
--    "ROAD_ADDRESS" VARCHAR(300),
--    "HOMEPAGE" VARCHAR(300),
--    "TEL" VARCHAR(300),
--    "FAX" VARCHAR(300),
--    "MALE_FEMALE" VARCHAR(300),
--    latitude double precision,
--    longitude double precision
--) TABLESPACE pg_default;
--
--ALTER TABLE
--    IF EXISTS public."TB_SCHOOL" OWNER to postgres;
--
---- 상가 매물 테이블
---- Table: public.TB_SELLING_AREA
--CREATE TABLE IF NOT EXISTS public."TB_SELLING_AREA" (
--    "SELLING_AREA_ID" serial primary key,
--    "SELLING_TYPE" VARCHAR(300),
--    "BUILDING_TYPE" VARCHAR(300),
--    "CURRENT_STATE" VARCHAR(300),
--    "ADDRESS" VARCHAR(300),
--    "AREA_SIZE" double precision,
--    "FLOOR_INFO" VARCHAR(300),
--    "DEPOSIT" integer,
--    "RATE_PER_MONTH" integer,
--    "PREMIUM" integer,
--    latitude double precision,
--    longitude double precision,
--    "RELATION_LINK" VARCHAR(300),
--    "SELLING_PRICE" bigint
--) TABLESPACE pg_default;
--
--ALTER TABLE
--    IF EXISTS public."TB_SELLING_AREA" OWNER to postgres;
--
---- 지하철 역정보 테이블
---- Table: public.TB_STATION
--CREATE TABLE IF NOT EXISTS public."TB_STATION" (
--    "STATION_ID" serial primary key,
--    "STATION_LINE" VARCHAR(300),
--    "STATION_NAME" VARCHAR(300),
--    "BRANCH_ADDRESS" VARCHAR(300),
--    "ROAD_ADDRESS" VARCHAR(300),
--    latitude double precision,
--    longitude double precision
--) TABLESPACE pg_default;
--
--ALTER TABLE
--    IF EXISTS public."TB_STATION" OWNER to postgres;
--
---- 버스정류장 테이블
---- Table: public.TB_STOP
--CREATE TABLE IF NOT EXISTS public."TB_STOP" (
--    "CITY_NAME" VARCHAR(300),
--    "STOP_NAME" VARCHAR(300),
--    "LATITUDE" double precision,
--    "LONGITUDE" double precision
--) TABLESPACE pg_default;
--
--ALTER TABLE
--    IF EXISTS public."TB_STOP" OWNER to postgres;
--
---- 관광지 테이블
---- Table: public.TB_TOUR
--CREATE TABLE IF NOT EXISTS public."TB_TOUR" (
--    "TOUR_ID" serial primary key,
--    "TOUR_NAME" VARCHAR(300),
--    "TOUR_ADDR_N" VARCHAR(300),
--    "TOUR_ADDR_O" VARCHAR(300),
--    latitude double precision,
--    longitude double precision
--) TABLESPACE pg_default;
--
--ALTER TABLE
--    IF EXISTS public."TB_TOUR" OWNER to postgres;