# import fitz
# path = "_dummy_src/report.pdf"
# doc = fitz.open(path)
# for page in doc:
#     text = page.get_text()
#     print(text)
#

import pandas as pd

df = pd.read_excel("../data_as_excels/paris.xlsx")
cols = ['PARIS_NAME', 'PARIS_ADDRESS', 'LATITUDE', 'LONGITUDE', 'AREA_SIZE',
        'OPEN_DATE', 'CLOSE_DATE', 'IS_OPEN_STATE', 'RIVAL_COUNT_NEAR_500',
        'RIVAL_COUNT_NEAR_1000', 'MONTHLY_SHOP_REVENUE',
        'MONTHLY_SHOP_SALE_TRANSACTION_COUNT', 'DAILY_FLOATING_POPULATION',
        'LIVING_WORKER_POPULATION', 'LIVING_WORKER_AVG_REVENUE',
        'LIVING_POPULATION', 'LIVING_POPULATION_AVG_REVENUE',
        'ATTRACTION_COUNT_NEAR_500', 'ATTRACTION_COUNT_NEAR_1000',
        'ACADEMY_COUNT_NEAR_500', 'ACADEMY_COUNT_NEAR_1000',
        'STOP_COUNT_NEAR_500', 'STOP_COUNT_NEAR_1000',
        'CROSSWALK_COUNT_NEAR_500', 'CROSSWALK_COUNT_NEAR_1000',
        'HOSPITAL_COUNT_NEAR_500', 'HOSPITAL_COUNT_NEAR_1000',
        'PARKING_COUNT_NEAR_500', 'PARKING_COUNT_NEAR_1000',
        'SCHOOL_COUNT_NEAR_500', 'SCHOOL_COUNT_NEAR_1000',
        'STATION_COUNT_NEAR_500', 'STATION_COUNT_NEAR_1000',
        'LIVING_COUNT_NEAR_500', 'LIVING_COUNT_NEAR_1000',
        'RIVAL_NEAR_DISTANCE', 'LIVING_NEAR_DISTANCE', 'SCHOOL_NEAR_DISTANCE',
        'ACADEMY_NEAR_DISTANCE', 'HOSPITAL_NEAR_DISTANCE',
        'STATION_NEAR_DISTANCE', 'STOP_NEAR_DISTANCE', 'PARKING_NEAR_DISTANCE',
        'ATTRACTION_NEAR_DISTANCE', 'CROSSWALK_NEAR_DISTANCE']

df = df[['AREA_SIZE', 'RIVAL_COUNT_NEAR_500',
         'RIVAL_COUNT_NEAR_1000', 'MONTHLY_SHOP_REVENUE',
         'MONTHLY_SHOP_SALE_TRANSACTION_COUNT', 'DAILY_FLOATING_POPULATION',
         'LIVING_WORKER_POPULATION', 'LIVING_WORKER_AVG_REVENUE',
         'LIVING_POPULATION', 'LIVING_POPULATION_AVG_REVENUE',
         'ATTRACTION_COUNT_NEAR_500', 'ATTRACTION_COUNT_NEAR_1000',
         'ACADEMY_COUNT_NEAR_500', 'ACADEMY_COUNT_NEAR_1000',
         'STOP_COUNT_NEAR_500', 'STOP_COUNT_NEAR_1000',
         'CROSSWALK_COUNT_NEAR_500', 'CROSSWALK_COUNT_NEAR_1000',
         'HOSPITAL_COUNT_NEAR_500', 'HOSPITAL_COUNT_NEAR_1000',
         'PARKING_COUNT_NEAR_500', 'PARKING_COUNT_NEAR_1000',
         'SCHOOL_COUNT_NEAR_500', 'SCHOOL_COUNT_NEAR_1000',
         'STATION_COUNT_NEAR_500', 'STATION_COUNT_NEAR_1000',
         'LIVING_COUNT_NEAR_500', 'LIVING_COUNT_NEAR_1000',
         'RIVAL_NEAR_DISTANCE', 'LIVING_NEAR_DISTANCE', 'SCHOOL_NEAR_DISTANCE',
         'ACADEMY_NEAR_DISTANCE', 'HOSPITAL_NEAR_DISTANCE',
         'STATION_NEAR_DISTANCE', 'STOP_NEAR_DISTANCE', 'PARKING_NEAR_DISTANCE',
         'ATTRACTION_NEAR_DISTANCE', 'CROSSWALK_NEAR_DISTANCE']]
print(df)
